Add save schedule lambda
csce-cups/tias pull request #48
Opened 2022-04-02 21:06 UTC by pulchroxloom

This lambda is invoked when the "Save Schedule" button is pressed. It takes as input the object returned from the postSchedulePeerTeachers lambda and saves the results into the database. It also attempts to return error codes aside from 200 on failure with the possibility of some useful information in the response body.

2022-04-02 21:39 UTC, benbeauchamp7 approved these changes
Short and sweet, looks good to me but won't know for sure until we start hitting it with data

2022-04-02 21:39 UTC, benbeauchamp7 commented on lambda/postSavedSchedule/index.js
> +            dbQuery += `($${paramIndex++}, $${paramIndex++})`;
These ++'s making me a little uncomfy, I know that it's fine though

2022-04-02 21:49 UTC, Shane-McGookey requested changes
Few changes recommended, otherwise looks good.

2022-04-02 21:49 UTC, Shane-McGookey commented on lambda/postSavedSchedule/index.js
> +            dbQuery += `($${paramIndex++}, $${paramIndex++})`;
This won't work without commas at the end of each set of values. Some logic will be needed to always add a comma except the last line.

2022-04-02 21:49 UTC, Shane-McGookey commented on lambda/postSavedSchedule/index.js
> +        response.body = JSON.stringify({err});
Would put a generic error message here; we don't want the user to directly see our error logs.

2022-04-03 15:41 UTC, Shane-McGookey requested changes
One small change, otherwise looks good.

2022-04-03 15:41 UTC, Shane-McGookey commented on lambda/postSavedSchedule/index.js
> +    console.log(dbRows);
Would remove this.

2022-04-03 15:46 UTC, merged